# Generated by Django 3.2.13 on 2023-06-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20230531_1820'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['travel_time'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Поезда'},
        ),
        migrations.AlterField(
            model_name='traintest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='cities.city', verbose_name='Откуда'),
        ),
    ]
